package cli

import (
	"github.com/agentstep/mvm/internal/state"
	"strings"
	"testing"
)

// TestRootfsScriptHasNoStrayApostrophe guards a whole class of failure that
// this project has been bitten by before (see the "never embed shell in Go
// strings" lesson).
//
// The rootfs build embeds a shell script inside a single-quoted `bash -c '...'`
// argument. A single apostrophe anywhere in that script — including in an
// English contraction inside a comment — closes the quote early. The failure is
// not a syntax error at the apostrophe: the rest of the script is reinterpreted,
// so the symptom shows up far away and reads as something else entirely. It
// cost a full rootfs build to diagnose, presenting as "here-document delimited
// by end-of-file" followed by the guest agent appearing not to exist.
//
// The script is generated by buildRootfsViaDocker; this reconstructs it the
// same way rather than duplicating it, so the test tracks edits automatically.
func TestRootfsScriptHasNoStrayApostrophe(t *testing.T) {
	script := rootfsBuildScript("docker", "/tmp/base.ext4", false)

	// Everything after the opening `bash -c '` up to the final `'` is inside the
	// quote. The opener is the only legitimate apostrophe before that point.
	const opener = "bash -c '"
	i := strings.Index(script, opener)
	if i < 0 {
		t.Fatalf("script no longer uses %q — update this test", opener)
	}
	body := script[i+len(opener):]

	// The script ends with the closing quote; everything before it must be free
	// of apostrophes.
	body = strings.TrimRight(body, "\n")
	body = strings.TrimSuffix(body, "'")

	if idx := strings.IndexByte(body, '\''); idx >= 0 {
		line := 1 + strings.Count(body[:idx], "\n")
		start := strings.LastIndexByte(body[:idx], '\n') + 1
		end := strings.IndexByte(body[idx:], '\n')
		if end < 0 {
			end = len(body) - idx
		}
		t.Errorf("apostrophe inside the single-quoted script at line %d — it will "+
			"terminate the bash -c quote and corrupt everything after it.\n  %s",
			line, body[start:idx+end])
	}
}

// TestRootfsScriptMountsDevShm pins the mount that Chromium (and anything else
// using shm_open) requires. Without it the guest has no POSIX shared memory and
// Chromium aborts at startup with a FATAL on /dev/shm.
func TestRootfsScriptMountsDevShm(t *testing.T) {
	script := rootfsBuildScript("docker", "/tmp/base.ext4", false)
	if !strings.Contains(script, "mount -t tmpfs") || !strings.Contains(script, "/dev/shm") {
		t.Error("rootfs init script must mount a tmpfs on /dev/shm")
	}
}

// TestRootfsScriptMakesRootShared pins the propagation setting the inner
// container depends on: without rshared here, a volume mounted after the
// container started is invisible inside it and vanishes on respawn.
func TestRootfsScriptMakesRootShared(t *testing.T) {
	script := rootfsBuildScript("docker", "/tmp/base.ext4", false)
	if !strings.Contains(script, "mount --make-rshared /") {
		t.Error("rootfs init script must make / rshared for mount propagation")
	}
}

func TestRootfsScriptUsesTheGivenRuntime(t *testing.T) {
	for _, rt := range []string{"docker", "/opt/homebrew/bin/container", "nerdctl"} {
		script := rootfsBuildScript(rt, "/tmp/base.ext4", false)
		if !strings.HasPrefix(strings.TrimSpace(script), rt+" run ") {
			t.Errorf("script for runtime %q does not invoke it: %.60s", rt, strings.TrimSpace(script))
		}
	}
}

// TestRootfsScriptBakesInGuestDocs pins that the sandbox self-description
// actually reaches the image. Without it an agent working inside treats the VM
// as an ordinary Linux box: it never snapshots before a risky change, never
// declares a service for a long-running process, and cannot recover from its
// own mistakes.
func TestRootfsScriptBakesInGuestDocs(t *testing.T) {
	script := rootfsBuildScript("docker", "/tmp/base.ext4", false)
	if !strings.Contains(script, "/rootfs"+state.GuestDocsPath) {
		t.Errorf("build does not write %s into the image", state.GuestDocsPath)
	}
	if !strings.Contains(script, "/rootfs"+state.GuestDocsAlias) {
		t.Errorf("build does not create the %s alias", state.GuestDocsAlias)
	}
	if !strings.Contains(script, "hardware-isolated sandbox") {
		t.Error("the docs body is missing from the build script")
	}
}
